# Set prefix to CTRL-A instead of CTRL-B
set -g prefix C-a
bind C-a send-prefix

# Enable mouse mode (clickable windows, panes, resizing)
set -g mouse on

# Please start from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Open new tabs, windows, splits in the current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Reorder windows # https://superuser.com/a/552493
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# Make the scroll chill a bit
bind -T copy-mode-vi WheelUpPane send-keys -X -N 3 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 3 scroll-down
bind -T copy-mode WheelUpPane send-keys -X -N 3 scroll-up
bind -T copy-mode WheelDownPane send-keys -X -N 3 scroll-down

# Display current path and command in the pane border
# Protip: read the tmux docs as i missed this whereas it's available for a decade or so
set -g pane-border-status top
set -g pane-border-lines double
set -g pane-border-format " #P: #{pane_current_path} | #{pane_current_command} "
set -g pane-active-border-style "fg=cyan"
set -g pane-border-style "fg=grey"

# Only show pane border status when a pane title has been set (i.e. SSH)
# Default pane title is the hostname, so we compare against it
set -g pane-border-status top
set -g pane-border-format "#{?#{==:#{pane_title},#{host}}, ,#[fg=black,bg=red] #{pane_title} #[default]}"

# Allow programs (and our LocalCommand) to set the pane title
set -g allow-rename on

# Don't wait, just escape
setw -g escape-time 0

# Send pane to specific window with fewer keystrokes
bind S command-prompt -p "send pane to:" "join-pane -t '%%'"

# Join marked pane to current window (mark with m, clear with M)
bind J join-pane

# Allow passthrough for notifications
set -g allow-passthrough all
set -g visual-bell off       # Don't show message
set -g bell-action none      # Don't send bell to terminal
set -g monitor-bell on       # But still flag the window in status bar

set -g window-status-bell-style 'fg=red,bg=default,bold'

###############
#### THEME ####
###############
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ",gnome*:RGB"

# Github colors for Tmux
set -g mode-style "fg=#c9d1d9,bg=#1f2428"

set -g message-style "fg=#c9d1d9,bg=#1f2428"
set -g message-command-style "fg=#c9d1d9,bg=#1f2428"

set -g pane-border-style "fg=#444c56"
set -g pane-active-border-style "fg=#0797d3"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#0797d3,bg=#1f2428"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#1f2428,bg=#0797d3,bold] #S #[fg=#0797d3,bg=#1f2428,nobold,nounderscore,noitalics]"
set -g status-right ""

setw -g window-status-activity-style "underscore,fg=#d1d5da,bg=#1f2428"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#24292e,bg=#1f2428"
setw -g window-status-format "#[fg=#1f2428,bg=#1f2428,nobold,nounderscore,noitalics]#[#{?window_bell_flag,fg=#ff6666 bold,fg=#666666 nobold},bg=#1f2428,nounderscore,noitalics] #I  #W #F #[fg=#1f2428,bg=#1f2428,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#1f2428,bg=#e1e4e8,nobold,nounderscore,noitalics]#[=#586069,bg=#e1e4e8,bold] #I  #W #F #[fg=#e1e4e8,bg=#1f2428,nobold,nounderscore,noitalics]"

set-option -g renumber-windows on

# Danke https://github.com/tmux-plugins/tmux-sensible
set -g history-limit 50000
set -g focus-events on
set -g display-time 4000
set -g status-interval 5
