-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

vim.keymap.del("n", "<space>l")
vim.keymap.set("v", "<", "<")
vim.keymap.set("v", ">", ">")
vim.keymap.set("n", "d", '"_d', { noremap = true, silent = true })
vim.keymap.set("n", "D", '"_D', { noremap = true, silent = true })
vim.keymap.set("v", "d", '"_d', { noremap = true, silent = true })
vim.keymap.set("n", "<space>d", '"_d', { noremap = true, silent = true })
vim.keymap.set("n", "<space>D", '"_D', { noremap = true, silent = true })
vim.keymap.set("v", "<space>d", '"_d', { noremap = true, silent = true })
vim.keymap.set("n", "<C-k>", function()
  require("dial.map").manipulate("increment", "normal")
end)
vim.keymap.set("n", "<C-j>", function()
  require("dial.map").manipulate("decrement", "normal")
end)
vim.keymap.set("n", "g<C-k>", function()
  require("dial.map").manipulate("increment", "gnormal")
end)
vim.keymap.set("n", "g<C-j>", function()
  require("dial.map").manipulate("decrement", "gnormal")
end)
vim.keymap.set("v", "<C-k>", function()
  require("dial.map").manipulate("increment", "visual")
end)
vim.keymap.set("v", "<C-j>", function()
  require("dial.map").manipulate("decrement", "visual")
end)
vim.keymap.set("v", "g<C-k>", function()
  require("dial.map").manipulate("increment", "gvisual")
end)
vim.keymap.set("v", "g<C-j>", function()
  require("dial.map").manipulate("decrement", "gvisual")
end)

-- Add keymap for git open command
vim.keymap.set("n", "<leader>go", function()
  vim.cmd("!git open")
end, { noremap = true, silent = true, desc = "Git open in browser" })
